apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
- cluster-role-binding.yaml
- deployment-nest-ms.yaml
- service-nest-ms.yaml
- ingress.yaml
- l4-service-to-service-auth-policy.yaml
- l7-principal-operations-auth-policy.yaml
- secret-provider.yaml