apiVersion: v1
kind: ServiceAccount
metadata:
  name: nest-ms-service-account
  namespace: test_base_ns
  annotations:
    argocd.argoproj.io/sync-wave: "0"
eks.amazonaws.com/role-arn: arn:aws:iam::{{.Values.accountId}}:role/dvss-dc-ap1-secrets-ssm-role